### ISSUE TITLE
Selection is shifted by one character, When twice input 'core:select-left'`

### ISSUE THREAD

**Issue by tomoya** [aki77/atom-emacs-plus#1]
In my case, Selection is shifted by one character when twice input `core:select-left`.

![selection](https://cloud.githubusercontent.com/assets/18009/8022147/7b41c1ac-0cfa-11e5-8f5f-59979f25227e.gif)

This problem just me?

**Comment by aki77** [comment]
Please try the latest version.

**Comment by tomoya** [comment]
I confirmed that issue has been fixed from v0.7.3
I'd like to continue to use this package thanks to you :+1:
