### ISSUE TITLE
Ctrl-P do not work

### ISSUE THREAD

**Issue by shishi** [aki77/atom-emacs-plus#10]
I am new for Atom. 
I clean installed Atom, I did not installed other packages, then I Installed emacs plus package. 
But Ctrl-p do not work for move above line, show fuzzy-finder. Should I do more setting?
Same problem happened after Atom restarted.

Windows 10, Atom 1.2.3, emacs plus 0.9.9

**Comment by aki77** [comment]
Please disable the fuzzy-finder keybindings.

[![Gyazo](https://i.gyazo.com/b6fa2562e9674bad1d2d6aa56bfe0144.png)](https://gyazo.com/b6fa2562e9674bad1d2d6aa56bfe0144)

**Comment by shishi** [comment]
:smile:

**Comment by tomoya** [comment]
:+1:
