### ISSUE TITLE
ctrl-a, ctrl-e keybindings etc do not work out of the box

### ISSUE THREAD

**Issue by ghost** [aki77/atom-emacs-plus#11]
I'm migrating from emacs to atom (Linux x64 version). I installed emacs-plus, restarted Atom, opened text file and tried a few emacs keybindings. Ctrl-a does 'select-all' instead of move-to-beginning-of-line.

I've seen the advice to install disable-keybindings package, but it's not clear how to disable only core keybindings that are conflicting with emacs-plus package. I can go to keymap.cson and try to write there something like:

'atom-workspace atom-text-editor':
  'ctrl-a': 'editor:move-to-beginning-of-line'

But it's not clear what's the point of emacs-plus then, I can just remap all keys I need in that way. I'm a bit confused about how that package should be used. Whether the expected user's behaviour is to go to keymap.cson and to remap all core keybindings manually or is it to disable all 'Core' keybindings with disable-keybindings package? From my point of view the expected behaviour is "it should just work", but I'm curious now how it should be used.

**Comment by aki77** [comment]
Please try the latest version.
