### ISSUE TITLE
ctrl-g not work

### ISSUE THREAD

**Issue by raytaylorlin** [aki77/atom-emacs-plus#12]
I want the `core:cancel`, but it triggers `go-to-line:toggle`

Windows 8.1, Atom 1.2.4, emacs plus 0.9.10

**Comment by raytaylorlin** [comment]
I added this in my `keymap.cson` and it worked.

```
'.platform-darwin, .platform-win32, .platform-linux':
  'ctrl-g': 'core:cancel'
```

**Comment by aki77** [comment]
Please disable the go-to-line keybindings.

[![https://gyazo.com/262f37045db138b0fe4b22c8df7ab802](https://i.gyazo.com/262f37045db138b0fe4b22c8df7ab802.png)](https://gyazo.com/262f37045db138b0fe4b22c8df7ab802)

**Comment by fredRos** [comment]
Thanks, disabling `go-to-line` worked for me, I had the same issue
