### ISSUE TITLE
ctrl-k response slowly

### ISSUE THREAD

**Issue by raytaylorlin** [aki77/atom-emacs-plus#13]
As the screencast you post in #7 , the `kill-line` command executed **immediately** when `ctrl-k` hit.

But in my atom(Windows 8.1, Atom 1.2.4, emacs plus 0.9.10), when I hit `ctrl-k` I have to wait for about 2 seconds before the `kill-line` command executed. I guess the reason is that there are many keybindings with the prefix `ctrl-k` defined in `Core`(`ctrl-k ctrl-0`, `ctrl-k ctrl-l` e.g.). Is there any solution?

**Comment by aki77** [comment]
Please use [disable-keybindings](https://atom.io/packages/disable-keybindings).

Prefix Keys settings: `ctrl-k`

  [![Gyazo](http://i.gyazo.com/663931390b87c82e89000b18ae710987.png)](http://gyazo.com/663931390b87c82e89000b18ae710987)
