### ISSUE TITLE
Text folding from gutter is broken

### ISSUE THREAD

**Issue by ivanpu** [aki77/atom-emacs-plus#14]
It looks like `set-mark` is triggered when I fold text with arrows in gutter.
The effect of this, is that almost any other action unfolds the text back.
- If I use cursor movement keys, the text is selected... after the unfold, with unfolded text as initial selection.
- If I click anywere with mouse, cursor jump there as expected, but again - with just folded text being unfolded.

To keep expected behaviour (not to trigger `set-mark`) I have to fold using keybinding, or to press `ESC` after folding from the gutter.

**Comment by shouya** [comment]
Link to the same issue on atom/atom: https://github.com/atom/atom/issues/10991

**Comment by aki77** [comment]
Please try the latest version.
