### ISSUE TITLE
I really like this package but I can not install it.

### ISSUE THREAD

**Issue by zalath** [aki77/atom-emacs-plus#15]
Installing “emacs-plus@0.9.11” failed.Hide output…

npm ERR! not a package C:\Users\Administrator.atom.apm\underscore-plus\1.6.6\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Administrator\AppData\Local\atom\app-1.4.1\resources\app\apm\bin\node.exe" "C:\Users\Administrator\AppData\Local\atom\app-1.4.1\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Administrator\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Administrator\.atom\.apmrc" "install" "C:\Users\ADMINI~1\AppData\Local\Temp\d-116029-5668-t1f2rd\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-116029-5668-1plklba\node_modules\emacs-plus\node_modules\underscore-plus\package.json
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-116029-5668-1plklba\node_modules\emacs-plus\node_modules\underscore-plus\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by aki77** [comment]
I have not received the same issue.
I think your PC environment is problem.
So please try re-install.

It is no reported on [underscore-plus](https://github.com/atom/underscore-plus/issues).

**Comment by zalath** [comment]
You are right, my old win7 may have some unknown problem, your package works really perfect on my win10.

**Comment by aki77** [comment]
:smiley:
