### ISSUE TITLE
Cmd-w (M-w) still bound to "Close Tab"

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [aki77/atom-emacs-plus#19]
Most of the keybindings I see [here](https://github.com/aki77/atom-emacs-plus/blob/master/keymaps/emacs.cson) work well, but for some reason "M-w" doesn't copy for me, and instead it still closes tabs (so it seems to still be bound to `core:close`). 

I don't have anything at all in my `keymap.cson`, so I don't know what could be wrong. 

In case it is helpful, I flipped `Cmd` and `Alt` in OS X to make working with Emacs (outside of Atom) easier.

![screenshot 2016-06-18 23 32 13](https://cloud.githubusercontent.com/assets/1993919/16175013/1a1183b8-35ad-11e6-9546-bd4feb43eb1c.png)

**Comment by StevenCHowell** [comment]
I do not have this issue on Linux, `M-w` copies the selected text as expected (can select text using mouse/`C-space`).

**Comment by tomoya** [comment]
Emacs Meta is handled Option key on Mac. Command key is independent as `cmd`.

You can investigate keybindings by Key Binding Resolver (`cmd-.`) if you want.
