### ISSUE TITLE
keybindings not working out of the box?

### ISSUE THREAD

**Issue by jots** [aki77/atom-emacs-plus#27]
Just installed this on atom 1.11.1  some keybindings work (such as ctrl-a) but others do not (such as ctrl-d and ctrl-e, and ctrl-k requires ctrl-k to be hit twice).  Is there a trick to getting keybindings to work?

**Comment by jots** [comment]
according to this:
https://discuss.atom.io/t/keyboard-shortcut-overriding-emmet-and-markdown-preview/14113/8

selector should maybe be:
'.editor:not(.mini)':

I changed it to that and placed in my keymap.cson and it appeared to work.

**Comment by aki77** [comment]
See also Issue #13.
