### ISSUE TITLE
Ctrl-k doesn't work properly

### ISSUE THREAD

**Issue by vvuk** [aki77/atom-emacs-plus#28]
I seem to need three `C-k`'s to kill a line... the first one doesn't do anything, though it seems to behave as if I had selected to the end of the line.  e.g. typing `C-a C-k` on a line that has `foo` in it has nothing visible happen, but if I then hit a key, say, `a`, the line is replaced with `a`.  If I do `C-a C-k C-k` then the contents of the line are deleted, but the line itself remains (as if I had just typed one C-k in emacs).  I need a third one to actually delete the line.

**Comment by EnigmaCurry** [comment]
Did you install (and configure) [disable-keybindings](https://atom.io/packages/disable-keybindings)?

**Comment by StevenCHowell** [comment]
What specific configurations are required in disable-keybindings?  It is not clear how to use this package [together with disable-keybindings and clipboard-plus] to fully change the keybindings.

I was getting lots of conflicting keybindings, then installed disable-keybindings and selected "All Bundled Packages" and "All Community Packages" the toggled "emacs-plus" off then on again but this only fixed some issues.  Here are examples of remaining examples:
- The first time I press `C-k` does nothing.  Pressing it a second time will cut the current line, a third time will cut the new line character.  Surprisingly, now pressing `C-y` will insert 2 lines (not just the cut line and new line character).
- `C-/` does not undo previous commands. In a file with no extension it does nothing on a line with text but it inserts the word `undefined` on empty lines.  In a file with the `.py` extension it toggles commenting out the current line. (`C-shift--` does undo)
- `C-x, C-f` does not prompt to open a file.
- `M-d` deletes a word forward but `M-h` does not delete a word backward (paralleling `C-d` and `C-h` for a single character).

I will add more as I find them.

**Comment by tomoya** [comment]
AFAIK, 'C-k' was used as prefix key on some packages (e.g. https://atom.io/packages/term3)
If Atom was handled 'C-k' as prefix key, Atom needs a few seconds gap while to kill a line.

In my case, I disabled term3 keybindings. After that, I was able to use `C-k` correctly.

```
    packagesWithKeymapsDisabled: [
      "term3"
    ]
```

I believe the best would be investigated your keybindings by Key Binding Resolver.

**Comment by zznull** [comment]
On Linux there's a bunch of keybindings that start with ctrl-k. These can be disabled with the following code in init.coffee:

    atom.keymaps.keyBindings = atom.keymaps.keyBindings.filter (binding, i) ->
      if binding.keystrokes.startsWith 'ctrl-k'
        binding.command.startsWith 'emacs-plus'
      else
        true
