### ISSUE TITLE
Cursor position is unusual after pasting multiple lines with ctrl-y

### ISSUE THREAD

**Issue by turnidge** [aki77/atom-emacs-plus#4]
When I kill multiple lines in regular, old emacs (by hitting ctrl-k several times) and then yank (ctrl-y) my cursor is placed at the end of the yanked text.  This lets me start typing immediately after the pasted text.

In emacs-plus, my cursor position seems like it is always after the first line of yanked text but before the second line -- basically kind of in the middle of the pasted text, which is unusual.  I would prefer to have the cursor at the end of the pasted region.

(not that a screenshot is needed, but here ya go...)
<img width="170" alt="screen shot 2015-07-14 at 11 39 59 pm" src="https://cloud.githubusercontent.com/assets/4804200/8692287/bea8da8a-2a81-11e5-9540-94280836ea7a.png">

(Thanks for working on this package, btw.  I appreciate it)

**Comment by aki77** [comment]
Please try the latest version.

**Comment by turnidge** [comment]
Thanks, fixed!
