### ISSUE TITLE
ctrl-p opens fuzzy finder instead of moving up

### ISSUE THREAD

**Issue by jcrosby** [aki77/atom-emacs-plus#5]
os: ubuntu 15.04

related plugins installed:
- clipboard-plus
- disable-keybindings
- emacs-plus

**Comment by aki77** [comment]
Please disable the fuzzy-finder keybindings.

[![Gyazo](https://i.gyazo.com/b6fa2562e9674bad1d2d6aa56bfe0144.png)](https://gyazo.com/b6fa2562e9674bad1d2d6aa56bfe0144)
