### ISSUE TITLE
Shift key and mark have unexpected behavior. 

### ISSUE THREAD

**Issue by avivo** [aki77/atom-emacs-plus#6]
I noticed that the Shift key acts the same as Control-Space, creating a persistent mark until I press Escape, and if I type anything it deletes the marked region. 

This seems like unexpected behavior, both because emacs doesn't have Shift do this and because marked regions don't behave this way by default (just verified on 24.4.1 with -q).

**Comment by aki77** [comment]
It is a specification for change the selection after the execution of the select command.(`editor:select-word`)

[![Gyazo](https://i.gyazo.com/c0bb2402fcadd79215d3672354bd7a27.gif)](https://gyazo.com/c0bb2402fcadd79215d3672354bd7a27)

**Comment by aaronjensen** [comment]
hmm, this is surprising to me too, both the originally described behavior and your example @aki77 

I think a ctrl-space should have to be required afterwards to go into mark mode. So you could do select word, then ctrl-space to expand. As it is it is too disruptive.

Some context, I maintain https://github.com/substantial/atomfiles and I would like to include emacs-plus as something that would not be disruptive to non-emacs users, but would be available for emacs users. Something like this would prevent me from doing that I think :frowning:

**Comment by aaronjensen** [comment]
One more gotcha, if you have multiple words selected w/ multiple cursors, I often want to hit ctrl-f to go to the end of my selection. Now it just expands it. Escape clears all my cursors but my current one. How do I get out of mark mode? Do I have to alt-w?

**Comment by aki77** [comment]
I got it. I think  I would like to fix near future.

**Comment by laurelnaiad** [comment]
Jumping into markmode on any shift+arrow key combo was making this unusable for me.

Commenting out [lines 46 and 47 in emacs.coffee](https://github.com/aki77/atom-emacs-plus/blob/master/lib/emacs.coffee#L46) stops this from happening.

I imagine this will foul up mark mode, but I'm willing to live without it to get my shift key back until this can be addressed properly. :smile: 

```

  selectionRangeChanged: (event = {}) =>
    {selection, newBufferRange} = event
    return unless selection?
    return if selection.isEmpty()
    return if @destroyed
    return if selection.cursor.destroyed?

    mark = Mark.for(selection.cursor)

    # taking out these lines is probably the wrong thing
    # to do, but it at least stops the shift-key-causes-markmode 
    # problem 
    # unless mark.isActive()
    #  mark.activate()
```

**Comment by ivanpu** [comment]
Reading this, I think #14 that I reported earlier might be related to this, or have similar origins.

**Comment by laurelnaiad** [comment]
By the way, if my hack fouled up mark mode, it didn't completely foul it up. It still seems to work, but I'm not all that fluent in emacs, so don't count on me to have put it through its paces.

**Comment by aki77** [comment]
Please try the latest version.
