### ISSUE TITLE
Ctrl-k behaviour differs from emacs

### ISSUE THREAD

**Issue by zznull** [aki77/atom-emacs-plus#7]
Ctrl-k doesn't simply kill from cursor to end of line. First press does nothing, second kills to end of line and the newline. Also, after killing a line and newline, the next key-press is ignored.

**Comment by aki77** [comment]
Can you post the screencast?

[![Gyazo](https://i.gyazo.com/06cd0e09866a35613009fdaecf0343b3.gif)](https://gyazo.com/06cd0e09866a35613009fdaecf0343b3)

**Comment by aki77** [comment]
Please try the latest version.
