### ISSUE TITLE
Cannot type backslash on Mac keyboard

### ISSUE THREAD

**Issue by jnous** [aki77/atom-emacs-plus#9]
Because alt-/ is mapped to

```
'atom-text-editor.emacs-plus:not([mini])':
  'alt-/': 'autocomplete-plus:activate'
```

it is not possible to type a backslash on a Mac keyboard (backslash is Option-Shift-7). A quick fix, losing the autocomplete-plus shortcut, is to override the above to value `unset!`.

**Comment by aki77** [comment]
It is not a backslash but a slash.
:question:

**Comment by tomoya** [comment]
@jnous, What is your keyboard layout?
My keyboard layout is English. In my case, There is slash key at left side on left shift.
And it is no problem. There is backslash at  above on return.

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/english_notebook.png)

see ref: https://support.apple.com/en-us/HT201794
